input_data: ./Dataset/LOCOMO/locomo10.json
memory_output_path: ./Result/LOCOMO/memochat/test/memory.json
prompt_path: ./Method/memochat/prompt_loco.json
results_output_path: ./Result/LOCOMO/memochat/test/result.json
openai_modelid: your/llm/model/path
base_url: http://localhost:8001/v1
api_key: "1"
token_file: ./Result/LOCOMO/memochat/test/token_tracker.json
