dataset_path: ./Dataset/LOCOMO/locomo10.json
memory_path: ./Result/LOCOMO/memoryos/gpt/mem_data
output_path: ./Result/LOCOMO/memoryos/gpt/result.json
llm_model: your/llm/model/path
llm_api_key: empty
llm_base_url: http://localhost:8000/v1
embedding_model_name: your/embedding/model/path
token_file: ./Result/LOCOMO/memoryos/token_tracker.json
