base_threshold: 0.4
batch_size: 64
collection_name: memory_tree

dimension: 384
embedding_batch_size: 256
embedding_model_name: all-MiniLM-L6-v2
llm_api_key: EMPTY
llm_base_url: http://localhost:8000/v1
llm_model: your/llm/model/path
llm_parallel_nums: 16
max_depth: 15
mode: vallina

rate: 0.5
retrieve_threshold: 0.3
save_name: memtree.pkl
top_k_retrieve: 10
vdb_name: milvus.db

dataset_name: locomo10
dataset_path: ./Dataset/LOCOMO/locomo10.json
output_path: ./Result/LOCOMO/memtree/test/result.json
token_file: ./Result/LOCOMO/memtree/test/token_tracker.json
num_processes: 4
