base_threshold: 0.4
collection_name: memory_tree
dimension: 384
embedding_batch_size: 256
embedding_model_name: minilm
llm_api_key: empty
llm_base_url: http://localhost:8001/v1
llm_model: your/llm/model/path
llm_parallel_nums: 16
max_depth: 15
rate: 0.5
save_name: memtree.pkl
top_k_retrieve: 10
vdb_name: milvus.db

num_processes: 10

dataset_path: ./Dataset/LOCOMO/locomodemo.json
memory_path: ./Result/LOCOMO/sota/test/mem_data
output_path: ./Result/LOCOMO/sota/test/result.json
